version: "3.9"

services:

  postgres-workflow:
    image: postgres:17.7
    environment:
      POSTGRES_DB: workflowdb
      POSTGRES_USER: workflow
      POSTGRES_PASSWORD: workflow
    volumes:
      - pgdata-workflow:/var/lib/postgresql/data

  postgres-task:
    image: postgres:17.7
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: task
      POSTGRES_PASSWORD: task
    volumes:
      - pgdata-task:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
    depends_on:
      - zookeeper

  workflow-service:
    build: ./workflowservice
    container_name: workflow-service
    depends_on:
      - postgres-workflow
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-workflow:5432/workflowdb
      SPRING_DATASOURCE_USERNAME: workflow
      SPRING_DATASOURCE_PASSWORD: workflow
    ports:
      - "8081:8080"

  task-service:
    build: ./taskservice
    container_name: task-service
    depends_on:
      - postgres-task
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-task:5432/taskdb
      SPRING_DATASOURCE_USERNAME: task
      SPRING_DATASOURCE_PASSWORD: task
    ports:
      - "8082:8080"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - workflow-service
      - task-service
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata-workflow:
  pgdata-task: